export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"
  | "QA Testing"
  | "UAT Coordination"
  | "Technical Documentation"
  | "Bug Tracking"
  | "IT Troubleshooting"
  | "System Administration"
  | "Yii2 Advanced" 
  | "RBAC"
  | "Middleware & Auth"
  | "CRUD"
  | "OpenRouter.ai"
  | "LLM Integration"
  | "UI/UX Design"
  | "Joomla CMS"
  | "Figma"
  | "Wireframing & Prototyping"
  | "Responsive Web Design"
  | "HTML5 & CSS3"
  | "Component Customization"
  | "Laravel Breeze(Auth)"
  | "Spatie(RBAC)"
  | "Filament(CRUD)"
  | "Github"
  | "Apache"
  | "OpenRouter.ai API"
  | "Yii2 Advance"
  | "muyuym(AdminLTE)"
  |  "mdmsoft(RBAC)"
  | "Gii(CRUD)"
  | "Joomla CMS Administrator"
  | "HTML5"
  | "CSS3"
  | "JavaScript"
  | "Canva"
  | "Graphic Design"
  | "Typography"
  | "Laravel 12"
  | "HTML/Blade"
  | "EmailJS"
  | "Render";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "MySQL"
  | "AI Integration"
  | "CMS"
  | "Design"
  | "Graphic Design";
  
  

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume"
  | "blogs";
